# basic setting
CONFIG_AMBIT_HARDWARE_VERSION="U12H449T00"
CONFIG_AMBIT_SOFTWARE_VERSION="V1.0.7.68"
CONFIG_AMBIT_UI_VERSION="2.0.35"
CONFIG_STRING_TBL_VERSION="1.0.7.68_2.1.46.1"
CONFIG_AMBIT_PRODUCT_NAME="RAXE500"
CONFIG_AMBIT_PRODUCT_DESCRIPTION="802.11ax Triple Band Gigabit Wireless Router RAXE500"
CONFIG_ETH_WAN_IF="eth0"
CONFIG_ETHERNET_LAN_IF_NAMES="eth1 eth2 eth3 eth4 eth5"
CONFIG_WIRELESS_INTERFACE_NUM=3
CONFIG_WIRELESS_INTERFACE="wl0,wl1,wl2"
CONFIG_WIRELESS_INTERFACE="wl0.1,wl1.1,wl2.1"
CONFIG_USBPORT_NUM=2

# for service or feature enable 
CONFIG_HTTPD_SERVER=y
CONFIG_UDHCPD_SERVER=y
CONFIG_SUPPORT_DAL=y
CONFIG_SUPPORT_BITDEFENDER=y

