#ifndef _WLAN5G1UTIL_H_
#define _WLAN5G1UTIL_H_
int set_wirelss_5g_1_ssid();
int set_wirelss_5g_1_channel();
int set_wirelss_5g_1_mode();
int set_wireless_5g_1_security_none();
int set_wireless_5g_1_security_wep();
int set_wireless_5g_1_security_wpa_psk();
int set_wireless_5g_1_security_wpa2_psk();
int set_wireless_5g_1_security_wpa_auto_psk();
int set_wireless_5g_1_security_wpa_enterprise();
int set_wireless_5g_1_security_wpa3_sae();
int set_wireless_5g_1_security_psk2_wpa3();
int set_wireless_5g_1_security();
int set_wireless_5g_1_radio_on_off();
int set_wireless_5g_1_ssid_broadcast();
int set_wireless_5g_1_rts_frag();
int set_wireless_5g_1_preamble();
int set_wireless_5g_1_beamforming();
int set_wireless_5g_1_mu_mimo();
int set_wireless_5g_1_ax_features();
int set_wireless_5g_1_led();
int set_wireless_5g_1_sche();
int set_wireless_5g_1_acl();
int set_wireless_5g_1_wme();
int set_wireless_5g_1_wds();
int set_wireless_5g_1_isolation();
int wireless_5g_1_config_update();
#endif
