#ifndef _WLAN2GUTIL_H_
#define _WLAN2GUTIL_H_
int set_wirelss_2g_ssid();
int set_wirelss_2g_channel();
int set_wirelss_2g_mode();
int set_wireless_2g_security_none();
int set_wireless_2g_security_wep();
int set_wireless_2g_security_wpa_psk();
int set_wireless_2g_security_wpa2_psk();
int set_wireless_2g_security_wpa_auto_psk();
int set_wireless_2g_security_wpa_enterprise();
int set_wireless_2g_security_wpa3_sae();
int set_wireless_2g_security_psk2_wpa3();
int set_wireless_2g_security();
int set_wireless_2g_radio_on_off();
int set_wireless_2g_ssid_broadcast();
int set_wireless_2g_rts_frag();
int set_wireless_2g_preamble();
int set_wireless_2g_beamforming();
int set_wireless_2g_mu_mimo();
int set_wireless_2g_ax_features();
int set_wireless_2g_led();
int set_wireless_2g_sche();
int set_wireless_2g_acl();
int set_wireless_2g_wme();
int set_wireless_2g_wds();
int set_wireless_2g_isolation();
int wireless_2g_config_update();
#endif
