version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  app:
    image: myapp:latest
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

